// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOH-yyhBgicJ5mgM2Rs_uF22BiNcCit1U',
    appId: '1:745683047609:android:38031080d931d02110f768',
    messagingSenderId: '745683047609',
    projectId: 'ulivery-e7a3e',
    storageBucket: 'ulivery-e7a3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQzzSZ7WqhdlD2JGV5CMw_gATwfnNdo9Q',
    appId: '1:745683047609:ios:1755b334a4a73df010f768',
    messagingSenderId: '745683047609',
    projectId: 'ulivery-e7a3e',
    storageBucket: 'ulivery-e7a3e.appspot.com',
    iosClientId: '745683047609-ncldt15mpo6akllvgrt25ulhvaltcsn6.apps.googleusercontent.com',
    iosBundleId: 'nl.ulivery.app',
  );
}
